[package]
name = "nagisalake-object-store"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nagisalake-protocol = { workspace = true }

aws-sdk-s3 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
